version: '3.3'

services:

  products:
    build:
      context: ./services/products
      dockerfile: Dockerfile-prod
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@products-db:5432/products_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@products-db:5432/products_test
    depends_on:  # <-- nuevo
      - products-db

  products-db:  # <-- nuevo
    build:
      context: ./services/products/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - products